# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, flake8-import-order]
        args: [--max-line-length=127, --max-complexity=10]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, types-requests]
        args: [--ignore-missing-imports]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [--configfile, .bandit]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: /Users/ajpri/Summer/AI_Audio/.venv/bin/python
        language: system
        types: [python]
        args: [-m, pytest, tests/, --maxfail=1, -q]
        pass_filenames: false
        always_run: true

      - id: safety
        name: safety
        entry: /Users/ajpri/Summer/AI_Audio/.venv/bin/python
        language: system
        args: [-m, safety, scan, --output, screen]
        pass_filenames: false
        always_run: true
